/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.cafe_management_app.ui.DashboardStaffUI;

import com.mycompany.cafe_management_app.model.BillDetail;

/**
 *
 * @author Administrator
 */
public class DishDetailsInBilIUI extends javax.swing.JPanel {

    /**
     * Creates new form DishDetailsInBilIUI
     */
    private BillDetail billDetail;

    public DishDetailsInBilIUI(BillDetail billDetail) {
        initComponents();
        this.billDetail = billDetail;

       quantityDish.setText(billDetail.getQuantity().toString());
       inventoryNameLabel.setText(billDetail.getDishDetail().getDish().getName());
       dishSizeLabel.setText(billDetail.getDishDetail().getSize());
       dishPriceLabel.setText(billDetail.getPrice().toString());

        // quantityDish.setText("1");
        // inventoryNameLabel.setText("Cafe");
        // dishSizeLabel.setText("S");
        // dishPriceLabel.setText("20.000");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inventoryNameLabel = new javax.swing.JLabel();
        dishSizeLabel = new javax.swing.JLabel();
        dishPriceLabel = new javax.swing.JLabel();
        quantityDish = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(380, 32));
        setPreferredSize(new java.awt.Dimension(380, 32));

        inventoryNameLabel.setText("Hong tra vai xoai");

        dishSizeLabel.setText("S");

        dishPriceLabel.setText("45.000");

        quantityDish.setText("1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(quantityDish, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inventoryNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(dishSizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(dishPriceLabel)
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inventoryNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(quantityDish)
                    .addComponent(dishSizeLabel)
                    .addComponent(dishPriceLabel))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dishPriceLabel;
    private javax.swing.JLabel dishSizeLabel;
    private javax.swing.JLabel inventoryNameLabel;
    private javax.swing.JLabel quantityDish;
    // End of variables declaration//GEN-END:variables
}
