/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.cafe_management_app.ui.DashboardStaffUI;

import com.mycompany.cafe_management_app.ui.*;
import com.mycompany.cafe_management_app.controller.DashboardStaffController.DetailsDishFunction;
import com.mycompany.cafe_management_app.model.Dish;
import javax.swing.JButton;

/**
 *
 * @author trung
 */
public class MenuItemStaffUI extends javax.swing.JPanel {

    /**
     * Creates new form MenuItem
     */
    private DetailsDishFunction detailsDishFunction;
    private Dish dish;

    public MenuItemStaffUI(Dish dish, DetailsDishFunction detailsDishFunction) {
        initComponents();
        this.dish = dish;
        this.nameDish.setText(dish.getName());
        this.detailsDishFunction = detailsDishFunction;
    }

   
    public JButton getDetailsBtn() {
        return detailsBtn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameDish = new javax.swing.JLabel();
        detailsBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(800, 32));
        setMinimumSize(new java.awt.Dimension(800, 32));
        setPreferredSize(new java.awt.Dimension(800, 32));

        nameDish.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameDish.setForeground(new java.awt.Color(51, 51, 51));
        nameDish.setText(".");

        detailsBtn.setBackground(new java.awt.Color(255, 255, 255));
        detailsBtn.setForeground(new java.awt.Color(51, 51, 51));
        detailsBtn.setText("Details");
        detailsBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        detailsBtn.setFocusPainted(false);
        detailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(nameDish, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                .addComponent(detailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(348, 348, 348))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameDish)
                    .addComponent(detailsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void detailsBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_detailsBtnActionPerformed
        // TODO add your handling code here:
        detailsDishFunction.showDetails(dish);
    }// GEN-LAST:event_detailsBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton detailsBtn;
    private javax.swing.JLabel nameDish;
    // End of variables declaration//GEN-END:variables
}
