/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.cafe_management_app.ui.DashboardStaffUI;

import com.mycompany.cafe_management_app.model.Dish;
import com.mycompany.cafe_management_app.model.DishDetail;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Administrator
 */
public class NewDishForm extends javax.swing.JPanel {

    /**
     * Creates new form NewDishForm
     */
    private Dish dish;

    public NewDishForm(Dish dish, String size, Double price) {
        initComponents();
        this.dish = dish;
        if (dish.getName() != null && size != null && price != null) {
            inventoryNameLabel.setText(dish.getName());
            dishSizeLabel.setText(size);
            dishPriceLabel.setText(price.toString());
        }
    }

    public Dish getDish() {
        return dish;
    }

    public void setDish(Dish dish) {
        this.dish = dish;
    }
    
    public String getInventoryNameLabel() {
        return inventoryNameLabel.getText();
    }

    public String getDishSizeLabel() {
        return dishSizeLabel.getText();
    }

    public String getDishPriceLabel() {
        return dishPriceLabel.getText();
    }

    public JButton getDeleteDishButton() {
        return deleteDishButton;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inventoryNameLabel = new javax.swing.JLabel();
        dishSizeLabel = new javax.swing.JLabel();
        dishPriceLabel = new javax.swing.JLabel();
        deleteDishButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(348, 32));
        setMinimumSize(new java.awt.Dimension(348, 32));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(348, 32));

        inventoryNameLabel.setForeground(new java.awt.Color(0, 0, 0));
        inventoryNameLabel.setText("Hong tra vai xoai");

        dishSizeLabel.setForeground(new java.awt.Color(0, 0, 0));
        dishSizeLabel.setText("S");

        dishPriceLabel.setForeground(new java.awt.Color(0, 0, 0));
        dishPriceLabel.setText("45.000");

        deleteDishButton.setBackground(new java.awt.Color(255, 0, 0));
        deleteDishButton.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        deleteDishButton.setForeground(new java.awt.Color(0, 0, 0));
        deleteDishButton.setIcon(new javax.swing.ImageIcon(
                "C:\\Users\\Administrator\\Desktop\\CafeManagementApp\\src\\main\\java\\com\\mycompany\\cafe_management_app\\asset\\image\\delete-button.png")); // NOI18N
        deleteDishButton.setText("X");
        deleteDishButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deleteDishButton.setPreferredSize(new java.awt.Dimension(17, 17));
        deleteDishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDishButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(inventoryNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48,
                                        Short.MAX_VALUE)
                                .addComponent(dishSizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(dishPriceLabel)
                                .addGap(41, 41, 41)
                                .addComponent(deleteDishButton, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(inventoryNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(dishSizeLabel)
                                        .addComponent(dishPriceLabel)
                                        .addComponent(deleteDishButton, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    private void deleteDishButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_deleteDishButtonActionPerformed
        // delete dish

    }// GEN-LAST:event_deleteDishButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteDishButton;
    private javax.swing.JLabel dishPriceLabel;
    private javax.swing.JLabel dishSizeLabel;
    private javax.swing.JLabel inventoryNameLabel;
    // End of variables declaration//GEN-END:variables
}
