/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.cafe_management_app.ui.DashboardStaffUI;

import com.mycompany.cafe_management_app.controller.BillDetailsController;
import com.mycompany.cafe_management_app.model.Bill;
import com.mycompany.cafe_management_app.model.Dish;
import com.mycompany.cafe_management_app.model.BillDetail;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

import javax.swing.JButton;

/**
 *
 * @author Trung
 */
public class OrderHistoryUI extends javax.swing.JPanel {

    /**
     * Creates new form StaffItem
     */
    private Bill bill;
  
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");

    public OrderHistoryUI(Bill bill) {
        initComponents();
        this.bill = bill;
      
        String formatDateTime = bill.getTimeCreated().format(formatter);
        timeLabel.setText(formatDateTime.toString());
        // format bill.getTotalPrice().toString() thành %,.0f

        String totalPrice = String.format("%,.0f", bill.getTotalPrice());
        String receiveAmount = String.format("%,.0f", bill.getReceivedAmount());
        String returnAmount = String.format("%,.0f", bill.getReturnedAmount());


        totalPriceLabel.setText(totalPrice);
        receiveAmountLabel.setText(receiveAmount);
        returnAmountLabel.setText(returnAmount);
        paymentMethodLabel.setText(bill.getPaymentMethod());
    }

    public JButton getdetailBill() {
        return detailBillButton;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timeLabel = new javax.swing.JLabel();
        totalPriceLabel = new javax.swing.JLabel();
        receiveAmountLabel = new javax.swing.JLabel();
        returnAmountLabel = new javax.swing.JLabel();
        paymentMethodLabel = new javax.swing.JLabel();
        detailBillButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(820, 40));
        setMinimumSize(new java.awt.Dimension(820, 40));
        setName(""); // NOI18N
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(820, 40));
        setRequestFocusEnabled(false);
        setVerifyInputWhenFocusTarget(false);

        timeLabel.setForeground(new java.awt.Color(51, 51, 51));
        timeLabel.setText(".");

        totalPriceLabel.setForeground(new java.awt.Color(51, 51, 51));
        totalPriceLabel.setText(".");

        receiveAmountLabel.setForeground(new java.awt.Color(51, 51, 51));
        receiveAmountLabel.setText(".");

        returnAmountLabel.setForeground(new java.awt.Color(51, 51, 51));
        returnAmountLabel.setText(".");

        paymentMethodLabel.setForeground(new java.awt.Color(51, 51, 51));
        paymentMethodLabel.setText(".");

        detailBillButton.setBackground(new java.awt.Color(255, 255, 255));
        detailBillButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        detailBillButton.setForeground(new java.awt.Color(0, 0, 0));
        detailBillButton.setText("Detail");
        detailBillButton.setMaximumSize(new java.awt.Dimension(72, 20));
        detailBillButton.setMinimumSize(new java.awt.Dimension(72, 20));
        detailBillButton.setPreferredSize(new java.awt.Dimension(72, 20));
        detailBillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailBillButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(totalPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(receiveAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(returnAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(paymentMethodLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detailBillButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(timeLabel)
                        .addComponent(totalPriceLabel)
                        .addComponent(receiveAmountLabel))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(returnAmountLabel)
                        .addComponent(paymentMethodLabel)
                        .addComponent(detailBillButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void detailBillButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_detailBillButtonActionPerformed
        new BillDetailsController(bill);
    }// GEN-LAST:event_detailBillButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton detailBillButton;
    private javax.swing.JLabel paymentMethodLabel;
    private javax.swing.JLabel receiveAmountLabel;
    private javax.swing.JLabel returnAmountLabel;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel totalPriceLabel;
    // End of variables declaration//GEN-END:variables
}
