/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.cafe_management_app.ui.DashboardStaffUI;

import com.mycompany.cafe_management_app.model.Bill;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author namho
 */
public class OrderHistory extends javax.swing.JPanel {

    /**
     * Creates new form StaffItem
     */
    private Bill bill;
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");


    public OrderHistory(Bill bill, LocalDateTime time, Double total, Double receiveAmount, Double returnAmount, String paymentMethod) {
       initComponents();
       this.bill = bill;
       if (time != null) {
           String formatDateTime = time.format(formatter);
           timeLabel.setText(formatDateTime.toString());
       }
       if (total != null) {
           totalPriceLabel.setText(total.toString());
       }
       if (receiveAmount != null) {
           receiveAmountLabel.setText(receiveAmount.toString());
       }
       if (returnAmount != null) {
           returnAmountLabel.setText(returnAmount.toString());
       }
       if (paymentMethod != null) {
           paymentMethodLabel.setText(paymentMethod);
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timeLabel = new javax.swing.JLabel();
        totalPriceLabel = new javax.swing.JLabel();
        receiveAmountLabel = new javax.swing.JLabel();
        returnAmountLabel = new javax.swing.JLabel();
        paymentMethodLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(800, 32));
        setMinimumSize(new java.awt.Dimension(800, 32));
        setName(""); // NOI18N
        setOpaque(false);
        setRequestFocusEnabled(false);
        setVerifyInputWhenFocusTarget(false);

        timeLabel.setForeground(new java.awt.Color(51, 51, 51));
        timeLabel.setText(".");

        totalPriceLabel.setForeground(new java.awt.Color(51, 51, 51));
        totalPriceLabel.setText(".");

        receiveAmountLabel.setForeground(new java.awt.Color(51, 51, 51));
        receiveAmountLabel.setText(".");

        returnAmountLabel.setForeground(new java.awt.Color(51, 51, 51));
        returnAmountLabel.setText(".");

        paymentMethodLabel.setForeground(new java.awt.Color(51, 51, 51));
        paymentMethodLabel.setText(".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(receiveAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(returnAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(paymentMethodLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(timeLabel)
                        .addComponent(totalPriceLabel)
                        .addComponent(receiveAmountLabel))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(returnAmountLabel)
                        .addComponent(paymentMethodLabel))))
        );
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel paymentMethodLabel;
    private javax.swing.JLabel receiveAmountLabel;
    private javax.swing.JLabel returnAmountLabel;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel totalPriceLabel;
    // End of variables declaration//GEN-END:variables
}
