/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.cafe_management_app.ui.DashboardStaffUI;

import com.mycompany.cafe_management_app.model.Bill;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author namho
 */
public class OrderHistory2 extends javax.swing.JPanel {

    /**
     * Creates new form StaffItem
     */
    private Bill bill;
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");


    public OrderHistory2(Bill bill, LocalDateTime time, Double total, Double receiveAmount, Double returnAmount) {
       initComponents();
       this.bill = bill;
       if (time != null) {
           String formatDateTime = time.format(formatter);
           timeLabel.setText(formatDateTime.toString());
       }
       if (total != null) {
           totalPriceLabel.setText(total.toString());
       }
       if (receiveAmount != null) {
           receiveAmountLabel.setText(receiveAmount.toString());
       }
       if (returnAmount != null) {
           returnAmountLabel.setText(returnAmount.toString());
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timeLabel = new javax.swing.JLabel();
        totalPriceLabel = new javax.swing.JLabel();
        receiveAmountLabel = new javax.swing.JLabel();
        returnAmountLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(800, 32));
        setMinimumSize(new java.awt.Dimension(800, 32));
        setPreferredSize(new java.awt.Dimension(800, 32));
        setLayout(null);

        timeLabel.setForeground(new java.awt.Color(51, 51, 51));
        timeLabel.setText(".");
        add(timeLabel);
        timeLabel.setBounds(30, 10, 170, 16);

        totalPriceLabel.setForeground(new java.awt.Color(51, 51, 51));
        totalPriceLabel.setText(".");
        add(totalPriceLabel);
        totalPriceLabel.setBounds(240, 10, 120, 16);

        receiveAmountLabel.setForeground(new java.awt.Color(51, 51, 51));
        receiveAmountLabel.setText(".");
        add(receiveAmountLabel);
        receiveAmountLabel.setBounds(400, 10, 120, 16);

        returnAmountLabel.setForeground(new java.awt.Color(51, 51, 51));
        returnAmountLabel.setText(".");
        add(returnAmountLabel);
        returnAmountLabel.setBounds(560, 10, 120, 16);

    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel totalPriceLabel;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel receiveAmountLabel;
    private javax.swing.JLabel returnAmountLabel;
    // End of variables declaration//GEN-END:variables
}
