/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cafe_management_app.ui.DashboardAdminUI;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author namho
 */
public class DashboardAdminUI extends javax.swing.JFrame {

    /**
     * Creates new form DashboardAdminUI
     */
    private CardLayout cards;
    
     
    private void selectBtn(JButton btn) {
        btn.setBackground(Color.WHITE);
        btn.setForeground(Color.getColor("#333333"));
    }
    
    private void unselectBtn(JButton btn) {
        btn.setForeground(Color.WHITE);
        btn.setBackground(Color.getColor("#333333"));
    }
    
    public DashboardAdminUI() {
        initComponents();
        cards = (CardLayout)(cardLayout.getLayout());
        selectBtn(navItemStaff);  
    }
    
    public JButton getAddStaffBtn() {
        return addStaff;
    }
    public JPanel getContainerListStaff() {
        return bgScrollPanelStaff;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        navItemStaff = new javax.swing.JButton();
        navItemMenu = new javax.swing.JButton();
        cardLayout = new javax.swing.JPanel();
        panelStaff = new javax.swing.JPanel();
        bgStaffPage = new com.mycompany.cafe_management_app.ui.DashboardAdminUI.BgPage();
        headerStaffPage = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        addStaff = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        contentStaffPage = new javax.swing.JPanel();
        scrollPanelStaff = new javax.swing.JScrollPane();
        bgScrollPanelStaff = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        bgMenuPage = new com.mycompany.cafe_management_app.ui.DashboardAdminUI.BgPage();
        headerMenuPage = new javax.swing.JPanel();
        addInventoryBtn = new javax.swing.JButton();
        contentMenuPage = new javax.swing.JPanel();
        scrollPanelMenu = new javax.swing.JScrollPane();
        bgScrollPanelMenu = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setEnabled(false);
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setMaximumSize(new java.awt.Dimension(180, 600));
        jPanel2.setMinimumSize(new java.awt.Dimension(180, 127));
        jPanel2.setPreferredSize(new java.awt.Dimension(180, 600));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WorkSpace");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setMaximumSize(new java.awt.Dimension(180, 32));
        jLabel1.setPreferredSize(new java.awt.Dimension(180, 32));
        jLabel1.setVerifyInputWhenFocusTarget(false);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, -1, -1));

        navItemStaff.setBackground(new java.awt.Color(51, 51, 51));
        navItemStaff.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        navItemStaff.setForeground(new java.awt.Color(255, 255, 255));
        navItemStaff.setText("Staff");
        navItemStaff.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        navItemStaff.setBorderPainted(false);
        navItemStaff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        navItemStaff.setFocusPainted(false);
        navItemStaff.setMaximumSize(new java.awt.Dimension(39, 35));
        navItemStaff.setMinimumSize(new java.awt.Dimension(39, 35));
        navItemStaff.setPreferredSize(new java.awt.Dimension(39, 35));
        navItemStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navItemStaffMouseClicked(evt);
            }
        });
        navItemStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navItemStaffActionPerformed(evt);
            }
        });
        jPanel2.add(navItemStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 60, 190, -1));

        navItemMenu.setBackground(new java.awt.Color(51, 51, 51));
        navItemMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        navItemMenu.setForeground(new java.awt.Color(255, 255, 255));
        navItemMenu.setText("Menu");
        navItemMenu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        navItemMenu.setBorderPainted(false);
        navItemMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        navItemMenu.setFocusPainted(false);
        navItemMenu.setPreferredSize(new java.awt.Dimension(49, 35));
        navItemMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navItemMenuMouseClicked(evt);
            }
        });
        navItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navItemMenuActionPerformed(evt);
            }
        });
        jPanel2.add(navItemMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 100, 190, -1));

        jPanel1.add(jPanel2);

        cardLayout.setBackground(new java.awt.Color(255, 255, 255));
        cardLayout.setPreferredSize(new java.awt.Dimension(820, 600));
        cardLayout.setLayout(new java.awt.CardLayout());

        panelStaff.setBackground(new java.awt.Color(255, 255, 255));
        panelStaff.setLayout(null);

        bgStaffPage.setLayout(new javax.swing.BoxLayout(bgStaffPage, javax.swing.BoxLayout.Y_AXIS));

        headerStaffPage.setBackground(new java.awt.Color(255, 255, 255));
        headerStaffPage.setMaximumSize(new java.awt.Dimension(820, 32));
        headerStaffPage.setMinimumSize(new java.awt.Dimension(820, 32));
        headerStaffPage.setPreferredSize(new java.awt.Dimension(820, 32));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Name");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Phone Number");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Date of Birth");

        addStaff.setBackground(new java.awt.Color(255, 255, 255));
        addStaff.setForeground(new java.awt.Color(51, 51, 51));
        addStaff.setText("new Staff +");
        addStaff.setActionCommand("addStaffBtn");
        addStaff.setBorder(null);
        addStaff.setBorderPainted(false);
        addStaff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addStaff.setFocusPainted(false);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Position");

        javax.swing.GroupLayout headerStaffPageLayout = new javax.swing.GroupLayout(headerStaffPage);
        headerStaffPage.setLayout(headerStaffPageLayout);
        headerStaffPageLayout.setHorizontalGroup(
            headerStaffPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerStaffPageLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
                .addComponent(addStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        headerStaffPageLayout.setVerticalGroup(
            headerStaffPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerStaffPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerStaffPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(addStaff)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bgStaffPage.add(headerStaffPage);

        contentStaffPage.setBackground(new java.awt.Color(255, 255, 255));
        contentStaffPage.setMaximumSize(new java.awt.Dimension(820, 568));
        contentStaffPage.setMinimumSize(new java.awt.Dimension(820, 568));
        contentStaffPage.setPreferredSize(new java.awt.Dimension(820, 568));

        scrollPanelStaff.setBackground(new java.awt.Color(255, 255, 255));
        scrollPanelStaff.setForeground(new java.awt.Color(255, 255, 255));
        scrollPanelStaff.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        bgScrollPanelStaff.setBackground(new java.awt.Color(255, 255, 255));
        bgScrollPanelStaff.setLayout(new javax.swing.BoxLayout(bgScrollPanelStaff, javax.swing.BoxLayout.Y_AXIS));
        scrollPanelStaff.setViewportView(bgScrollPanelStaff);

        javax.swing.GroupLayout contentStaffPageLayout = new javax.swing.GroupLayout(contentStaffPage);
        contentStaffPage.setLayout(contentStaffPageLayout);
        contentStaffPageLayout.setHorizontalGroup(
            contentStaffPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPanelStaff)
        );
        contentStaffPageLayout.setVerticalGroup(
            contentStaffPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPanelStaff, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        bgStaffPage.add(contentStaffPage);

        panelStaff.add(bgStaffPage);
        bgStaffPage.setBounds(0, 0, 820, 600);

        cardLayout.add(panelStaff, "cardStaff");

        panelMenu.setBackground(new java.awt.Color(255, 255, 255));
        panelMenu.setLayout(null);

        bgMenuPage.setLayout(new javax.swing.BoxLayout(bgMenuPage, javax.swing.BoxLayout.Y_AXIS));

        headerMenuPage.setMaximumSize(new java.awt.Dimension(820, 32));
        headerMenuPage.setMinimumSize(new java.awt.Dimension(820, 32));
        headerMenuPage.setOpaque(false);
        headerMenuPage.setPreferredSize(new java.awt.Dimension(820, 32));

        addInventoryBtn.setBackground(new java.awt.Color(255, 255, 255));
        addInventoryBtn.setForeground(new java.awt.Color(51, 51, 51));
        addInventoryBtn.setText("new Inventory +");
        addInventoryBtn.setActionCommand("addInventoryBtn");
        addInventoryBtn.setBorder(null);

        javax.swing.GroupLayout headerMenuPageLayout = new javax.swing.GroupLayout(headerMenuPage);
        headerMenuPage.setLayout(headerMenuPageLayout);
        headerMenuPageLayout.setHorizontalGroup(
            headerMenuPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerMenuPageLayout.createSequentialGroup()
                .addContainerGap(707, Short.MAX_VALUE)
                .addComponent(addInventoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        headerMenuPageLayout.setVerticalGroup(
            headerMenuPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerMenuPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addInventoryBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addContainerGap())
        );

        addInventoryBtn.getAccessibleContext().setAccessibleName("addInventoryBtn");

        bgMenuPage.add(headerMenuPage);

        contentMenuPage.setAutoscrolls(true);
        contentMenuPage.setOpaque(false);

        scrollPanelMenu.setBackground(new java.awt.Color(255, 255, 255));
        scrollPanelMenu.setForeground(new java.awt.Color(255, 255, 255));
        scrollPanelMenu.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPanelMenu.setOpaque(false);

        bgScrollPanelMenu.setBackground(new java.awt.Color(255, 255, 255));
        bgScrollPanelMenu.setLayout(new javax.swing.BoxLayout(bgScrollPanelMenu, javax.swing.BoxLayout.Y_AXIS));
        scrollPanelMenu.setViewportView(bgScrollPanelMenu);

        javax.swing.GroupLayout contentMenuPageLayout = new javax.swing.GroupLayout(contentMenuPage);
        contentMenuPage.setLayout(contentMenuPageLayout);
        contentMenuPageLayout.setHorizontalGroup(
            contentMenuPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPanelMenu)
        );
        contentMenuPageLayout.setVerticalGroup(
            contentMenuPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
        );

        bgMenuPage.add(contentMenuPage);

        panelMenu.add(bgMenuPage);
        bgMenuPage.setBounds(0, 0, 820, 600);

        cardLayout.add(panelMenu, "cardMenu");

        jPanel1.add(cardLayout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void navItemStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navItemStaffActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_navItemStaffActionPerformed

    private void navItemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navItemMenuActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_navItemMenuActionPerformed

    private void navItemMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navItemMenuMouseClicked
        // TODO add your handling code here:
         cards.show(cardLayout, "cardMenu");
         selectBtn(navItemMenu);
         unselectBtn(navItemStaff);
    }//GEN-LAST:event_navItemMenuMouseClicked

    private void navItemStaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navItemStaffMouseClicked
        // TODO add your handling code here:
        cards.show(cardLayout, "cardStaff");
        navItemStaff.setBackground(Color.red);
        selectBtn(navItemStaff);
        unselectBtn(navItemMenu );
    }//GEN-LAST:event_navItemStaffMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardAdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardAdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardAdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardAdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardAdminUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addInventoryBtn;
    private javax.swing.JButton addStaff;
    private com.mycompany.cafe_management_app.ui.DashboardAdminUI.BgPage bgMenuPage;
    private javax.swing.JPanel bgScrollPanelMenu;
    private javax.swing.JPanel bgScrollPanelStaff;
    private com.mycompany.cafe_management_app.ui.DashboardAdminUI.BgPage bgStaffPage;
    private javax.swing.JPanel cardLayout;
    private javax.swing.JPanel contentMenuPage;
    private javax.swing.JPanel contentStaffPage;
    private javax.swing.JPanel headerMenuPage;
    private javax.swing.JPanel headerStaffPage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton navItemMenu;
    private javax.swing.JButton navItemStaff;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelStaff;
    private javax.swing.JScrollPane scrollPanelMenu;
    private javax.swing.JScrollPane scrollPanelStaff;
    // End of variables declaration//GEN-END:variables

}
