/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.cafe_management_app.ui.DashboardAdminUI;

import com.mycompany.cafe_management_app.model.Staff;
import com.mycompany.cafe_management_app.util.callback.EditEvent;
import com.mycompany.cafe_management_app.util.callback.DeleteEvent;

/**
 *
 * @author namho
 */
public class StaffItem extends javax.swing.JPanel {

    /**
     * Creates new form StaffItem
     */
    private EditEvent editEvent;
    private DeleteEvent deleteEvent;
    private Staff staff;

    public StaffItem(Staff staff, String name, String DoB, String phoneNumber, String position, EditEvent editEvent, DeleteEvent deleteEvent) {
       initComponents();
       nameLabel.setText(name);
       dobLabel.setText(DoB);
       phoneLabel.setText(phoneNumber);
       positionLabel.setText(position);
       this.staff = staff;
       this.deleteEvent = deleteEvent;
       this.editEvent = editEvent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        dobLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        positionLabel = new javax.swing.JLabel();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(800, 32));
        setMinimumSize(new java.awt.Dimension(800, 32));
        setPreferredSize(new java.awt.Dimension(800, 32));
        setLayout(null);

        nameLabel.setForeground(new java.awt.Color(51, 51, 51));
        nameLabel.setText(".");
        add(nameLabel);
        nameLabel.setBounds(10, 10, 100, 16);

        dobLabel.setForeground(new java.awt.Color(51, 51, 51));
        dobLabel.setText(".");
        add(dobLabel);
        dobLabel.setBounds(150, 10, 100, 16);

        phoneLabel.setForeground(new java.awt.Color(51, 51, 51));
        phoneLabel.setText(".");
        add(phoneLabel);
        phoneLabel.setBounds(320, 10, 80, 16);

        positionLabel.setForeground(new java.awt.Color(51, 51, 51));
        positionLabel.setText(".");
        add(positionLabel);
        positionLabel.setBounds(470, 10, 80, 16);

        editBtn.setBackground(new java.awt.Color(255, 255, 255));
        editBtn.setForeground(new java.awt.Color(51, 51, 51));
        editBtn.setText("Edit");
        editBtn.setBorder(null);
        editBtn.setBorderPainted(false);
        editBtn.setFocusable(false);
        editBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editBtnMouseClicked(evt);
            }
        });
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });
        add(editBtn);
        editBtn.setBounds(560, 10, 70, 20);

        deleteBtn.setBackground(new java.awt.Color(255, 255, 255));
        deleteBtn.setForeground(new java.awt.Color(255, 51, 51));
        deleteBtn.setText("Delete");
        deleteBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        deleteBtn.setBorderPainted(false);
        deleteBtn.setFocusable(false);
        deleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBtnMouseClicked(evt);
            }
        });
        add(deleteBtn);
        deleteBtn.setBounds(690, 10, 60, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editBtnActionPerformed

    private void editBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBtnMouseClicked
        // TODO add your handling code here:
        this.editEvent.edit(staff);
    }//GEN-LAST:event_editBtnMouseClicked

    private void deleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseClicked
        // TODO add your handling code here:
        this.deleteEvent.delete(staff);
    }//GEN-LAST:event_deleteBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JLabel positionLabel;
    // End of variables declaration//GEN-END:variables
}
