/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.cafe_management_app.ui.DashboardAdminUI;

/**
 *
 * @author namho
 */
public class StaffItem extends javax.swing.JPanel {

    /**
     * Creates new form StaffItem
     */
    public StaffItem(String name, String DoB, String phoneNumber) {
       initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        dobLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(800, 32));
        setMinimumSize(new java.awt.Dimension(800, 32));
        setPreferredSize(new java.awt.Dimension(800, 32));
        setLayout(null);

        nameLabel.setForeground(new java.awt.Color(51, 51, 51));
        nameLabel.setText("dsdasdsdasd");
        add(nameLabel);
        nameLabel.setBounds(40, 10, 100, 16);

        dobLabel.setForeground(new java.awt.Color(51, 51, 51));
        dobLabel.setText("dsdadsdasdasd");
        add(dobLabel);
        dobLabel.setBounds(260, 10, 80, 16);

        phoneLabel.setForeground(new java.awt.Color(51, 51, 51));
        phoneLabel.setText("dasdadsdasdasd");
        add(phoneLabel);
        phoneLabel.setBounds(420, 10, 80, 16);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dobLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel phoneLabel;
    // End of variables declaration//GEN-END:variables
}
